# Generated by Django 4.2.3 on 2023-12-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom2', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='products', to='ecom2.productgroup'),
        ),
    ]
